### ISSUE TITLE
No feature "FPU"

### ISSUE THREAD

**Issue by FrozenDroid** [drone-os/drone-stm32-map#1]
Hi there, thanks so much for this amazing project!

I ran `drone new --device stm32l4x6 --flash-size 1024k --ram-size 96k hello-world`, and when running `just build`, it returns an error:

```
error: failed to select a version for `drone-stm32-map`.
    ... required by package `hello-world v0.1.0`
versions that meet the requirements `^0.10.0` are: 0.10.1, 0.10.0

the package `hello-world` depends on `drone-stm32-map`, with features: `fpu` but `drone-stm32-map` does not have these features.


failed to select a version for `drone-stm32-map` which could resolve this conflict
```

**Comment by valff** [comment]
Hi @FrozenDroid, thanks for your interest!

This is a bug in the new project template. I will fix it soon. If you don't want to wait, you can change your generated Cargo.toml from this:

```toml
drone-cortex-m = { version = "0.10.0" }
drone-stm32-map = { version = "0.10.0", features = ["stm32l4x6", "fpu"] }
```

To this:

```toml
drone-cortex-m = { version = "0.10.0", features = ["fpu"] }
drone-stm32-map = { version = "0.10.0", features = ["stm32l4x6"] }
```

**Comment by valff** [comment]
Fixed in `drone` v0.10.1

Please update it with `cargo +nightly install drone --force`.

**Comment by FrozenDroid** [comment]
Thanks for the quick response! Which nightly are you running? I'm getting an error from futures-util. I'll elaborate more when I'm home.

**Comment by valff** [comment]
I'm currently using nightly-2019-09-05. I will check with the recent nightly soon. Thanks for the report.

**Comment by valff** [comment]
I checked with nightly-2019-09-27 and it builds without errors on my machine. I wonder what was the error you got. Generally it should be ok to use the latest nightly with all available components according to this table: https://rust-lang.github.io/rustup-components-history/

**Comment by FrozenDroid** [comment]
With the latest nightly as of today (rustc 1.40.0-nightly (22bc9e1d9 2019-09-30)), I'm getting multiple errors such as:
```
error: <inline asm>:1:19: error: brackets expression not supported on this target
        strexb %al, %al, [%rcx]
                         ^

   --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/drone-cortex-m-0.10.1/src/reg/atomic.rs:204:17
    |
204 | /                 asm!($strex
205 | |                      : "=r"(status)
206 | |                      : "r"(self), "r"(address)
207 | |                      :
208 | |                      : "volatile"
209 | |                 );
    | |__________________^
...
218 |   atomic_bits!(u8, "ldrexb $0, [$1]", "strexb $0, $1, [$2]");
    |   ----------------------------------------------------------- in this macro invocation
```

**Comment by FrozenDroid** [comment]
Never mind, I'm silly. I did `cargo build` instead of `just build`
