### ISSUE TITLE
Unclear where to put generic drivers

### ISSUE THREAD

**Issue by dflemstr** [drone-os/drone-stm32-map#3]
I want to contribute an SPI driver leveraging `drone_stm32_map_periph_spi::SpiPeriph`.  Code organization wise, does that belong in this group of crates, or should a new `drone-stm32` crate be created for that purpose?

**Comment by valff** [comment]
Thanks for your interest! There is [drone-stm32-drv](https://github.com/centosa/drone-stm32-drv) for this purpose. We're already using it in our project, but it isn't documented and polished yet. It already has a generic SPI driver, but the API is very basic and thin. If you have a proposal for a better API, it is very welcomed.

The crate uses [drone_core::inventory](https://api.drone-os.com/drone-core/0.10/drone_core/inventory/index.html) module to track the power state of peripherals in the compile-time. I advice you to read its documentation first.

**Comment by dflemstr** [comment]
Awesome! I will try to leverage that crate and see how easy to use the API would be for my use-case.  I will get back with any potential feedback!
