### ISSUE TITLE
svd2rust

### ISSUE THREAD

**Issue by FrozenDroid** [drone-os/drone-stm32-map#5]
Hi!

Just curiosity; Why wasn't svd2rust chosen to generate Rust code out of svd files?

**Comment by valff** [comment]
Hi! Because we have our own rich API for memory-mapped register bindings. Please take a look at this module: https://api.drone-os.com/drone-cortex-m/0.10/drone_cortex_m/reg/index.html And our interrupt bindings are also completely different.
