### ISSUE TITLE
No support for `cluster` in SVD files

### ISSUE THREAD

**Issue by FrozenDroid** [drone-os/drone-stm32-map#6]
Hi,

I am trying to create a register map for the nrf9160, however in their SVD files, they use clusters in the peripheral registers.
I'll see if I can write up a solution to this.

**Comment by valff** [comment]
Hi. Currently `drone-stm32-map-svd` subcrate (`svd` directory) supports only features needed to parse ST's SVD files. The plan is to extract it to a new `drone-svd` repo and make it more universal.

**Comment by FrozenDroid** [comment]
Would you have any objections to use the [svd](https://github.com/rust-embedded/svd) crate to parse the SVD files? We can then use the structs to make the drone mappings. I personally think that'd be the easiest way to go about it, as there are still quite a few things left to implement.

**Comment by valff** [comment]
I'm not sure if it would be easy to modify SVD structures on the fly like it is done in https://github.com/drone-os/drone-stm32-map/blob/master/svd/src/lib.rs I would like to keep SVD files unmodified and apply fixes declaratively. Also I wonder why that crate uses `xmltree` instead of `serde-xml-rs`?

**Comment by FrozenDroid** [comment]
Hmm, yeah, those are fair points.
Will you have time to implement the extra features needed for the nrf9160, or shall I get on it?

**Comment by valff** [comment]
I think I will extract `drone-svd` and create initial `drone-nrf-map` (including nrf9160) in the next few days.

**Comment by valff** [comment]
This was implemented.
